image: ubuntu:14.04
  
upload_egg:
  script:
    # add git as part of the egg upload
    - apt-get update -y && apt-get install -y git
    # Check if the package is actually installable
    - apt-get install -y python curl
    - apt-get install -y python-dev libffi-dev
    - curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
    - python get-pip.py
    - pip install pyOpenSSL ndg-httpsclient pyasn1
    - pip install requests[security]
    - pip install tornado==4.5.1
    - pip install .
    - pip show $CI_PROJECT_NAME

    # Upload to pypicloud
  #   - pip install twine
  #   - python setup.py sdist
  #   - twine upload --repository-url $PYPI_SERVER --username $USERNAME --password $PASSWORD dist/*
  # only:
  #   - master
  